//
// Created by Vladimir Arsenijevic on 28.5.2026.
//

#include "Parser.h"
#include "Parser_internal.h"
#include <iostream>

Parser::Parser(std::unordered_set<std::string> initialClassNames, GenericRegistry* sharedRegistry)
    : classNames(std::move(initialClassNames)) {
    if (sharedRegistry) gen_ = sharedRegistry;
}

Program Parser::parse(const std::vector<Token>& inputTokens, const std::string& filenameStr,
                      bool runMono) {
    tokens   = std::vector<Token>(inputTokens);
    current  = 0;
    filename = filenameStr;

    // Module namespacing: read this file's `module`/symbol-imports, register its members (into the
    // possibly-shared registry), then rewrite the token stream so every name carries its module
    // prefix — exactly like generic mangling. Skipped entirely when no module is in play, so a
    // module-less program's tokens (and thus its IR) are byte-identical to before.
    scanModuleDirectives(tokens, currentModule_, importBindings_, ambiguousImports_);
    scanModuleMembers(tokens, currentModule_, gen_->moduleTypes, gen_->moduleFuncs, gen_->moduleNames);
    if (!currentModule_.empty() || !gen_->moduleNames.empty())
        tokens = qualifyTokens(tokens, currentModule_, importBindings_, ambiguousImports_,
                               gen_->moduleTypes, gen_->moduleFuncs, gen_->moduleNames);

    // Register this file's template/class names (idempotent if pre-seeded by the caller).
    prescanTemplateNames(tokens);

    Program program;
    while (!isAtEnd()) {
        // Consume module-namespacing directives (already recorded above); they emit no AST node.
        if (check(TokenType::MODULE)) {                 // `module NAME ('.' NAME)* ;`
            advance();
            if (check(TokenType::IDENTIFIER)) {
                advance();
                while (check(TokenType::DOT) && peekNext().type == TokenType::IDENTIFIER) {
                    advance();   // '.'
                    advance();   // IDENT
                }
            }
            (void)match({ TokenType::SEMICOLON });
            continue;
        }
        if (check(TokenType::IMPORT) && peekNext().type != TokenType::STRING) {   // `import a.B ;`
            while (!isAtEnd() && !check(TokenType::SEMICOLON)) advance();
            (void)match({ TokenType::SEMICOLON });
            continue;
        }
        if (tryCaptureClassTemplate())    continue;   // generic decls produce no AST node
        if (tryCaptureFunctionTemplate()) continue;
        if (tryCaptureImplTemplate())     continue;
        program.declarations.push_back(parseDeclaration());
    }

    // Emit any canonical `Call$…` trait declarations generated by Call bounds / `impl Call` / lambdas
    // (deduped across files via the shared registry) before the concrete decls that reference them.
    for (Stmt& t : pendingCallTraits_) program.declarations.push_back(std::move(t));
    pendingCallTraits_.clear();
    for (Stmt& d : pendingLambdaDecls_) program.declarations.push_back(std::move(d));
    pendingLambdaDecls_.clear();

    if (runMono) runMonomorphization(program);   // expand instantiations now (single-file path)
    return program;
}

// ============================================================
// Token stream navigation
// ============================================================

const Token& Parser::peek() const {
    return tokens[current];
}

const Token& Parser::peekNext() const {
    if (current + 1 >= tokens.size()) return tokens.back();
    return tokens[current + 1];
}

const Token& Parser::previous() const {
    return tokens[current - 1];
}

bool Parser::isAtEnd() const {
    return peek().type == TokenType::END_OF_FILE;
}

const Token& Parser::advance() {
    if (!isAtEnd()) current++;
    return previous();
}

bool Parser::check(TokenType type) const {
    return !isAtEnd() && peek().type == type;
}

bool Parser::match(std::initializer_list<TokenType> types) {
    for (TokenType type : types) {
        if (check(type)) { advance(); return true; }
    }
    return false;
}

const Token& Parser::consume(TokenType type, const std::string& msg) {
    if (check(type)) return advance();
    throw error(peek(), msg);
}

// ============================================================
// Error handling
// ============================================================

void Parser::throwTypeExpected(const std::string& what) {
    const Token& t = peek();
    std::string msg = "expected " + what;
    if (t.type == TokenType::IDENTIFIER) {
        // A bare identifier in type position looks like a type name that isn't declared.
        msg += ", but '" + t.lexeme + "' is not a known type "
               "(expected a primitive, a declared class or enum, or Self)";
        if (inImplBlock_)
            msg += ". Note: an `impl` only sees the type parameters it declares — to use `T`, "
                   "write `impl<T> Trait for Foo<T> { ... }` (declare `T` right after `impl`)";
    } else {
        msg += ", but found '" + t.lexeme + "'";
    }
    throw error(t, msg);
}

ParseError Parser::error(const Token& token, const std::string& msg) {
    std::string prefix = filename.empty() ? "" : filename + ":";
    std::string formatted = prefix + std::to_string(token.line) + ": error: " + msg;
    // Do NOT print here — the thrown ParseError carries the message, and the top-level
    // handler (GG::run / the test helpers) prints it exactly once. Printing here as well
    // duplicated every parse error, and printed speculative errors that were recovered
    // from during template/lambda look-ahead (which catch and discard the exception).
    return ParseError(formatted);
}

void Parser::synchronize() {
    advance();
    while (!isAtEnd()) {
        if (previous().type == TokenType::SEMICOLON) return;
        switch (peek().type) {
            case TokenType::IF:
            case TokenType::WHILE:
            case TokenType::FOR:
            case TokenType::RETURN:
            case TokenType::BREAK:
            case TokenType::CONTINUE:
            case TokenType::IMPORT:
            case TokenType::EXTERN:
            case TokenType::I8:
            case TokenType::I16:
            case TokenType::I32:
            case TokenType::I64:
            case TokenType::U8:
            case TokenType::U16:
            case TokenType::U32:
            case TokenType::U64:
            case TokenType::F32:
            case TokenType::F64:
            case TokenType::BOOL:
            case TokenType::CHAR_TYPE:
            case TokenType::VOID:
            case TokenType::PTR:
                return;
            default:
                break;
        }
        advance();
    }
}

// ============================================================
// Helpers
// ============================================================

bool Parser::isTypeName() const {
    switch (peek().type) {
        case TokenType::I8:
        case TokenType::I16:
        case TokenType::I32:
        case TokenType::I64:
        case TokenType::U8:
        case TokenType::U16:
        case TokenType::U32:
        case TokenType::U64:
        case TokenType::F32:
        case TokenType::F64:
        case TokenType::BOOL:
        case TokenType::CHAR_TYPE:
        case TokenType::VOID:
        case TokenType::PTR:
        case TokenType::STR:
            return true;
        case TokenType::SELF:
            return true;   // valid only inside trait/impl bodies; semantic enforces that
        case TokenType::IDENTIFIER:
            return classNames.count(peek().lexeme) > 0 || gen_->classNames.count(peek().lexeme) > 0;
        case TokenType::LEFT_PAREN:
            // A tuple type `(T1, T2, …)` starts with '('. Confirm it is a full, valid tuple-type
            // span (≥ 2 type elements, closing ')') so a grouped expression `(a + b)` or a tuple
            // *literal* `(a, b)` (whose elements are values, not types) is not mistaken for a type.
            return typeSpanAt(current) > 0;
        default:
            return false;
    }
}

// A type with an optional trailing `?` (nullable). `T?` → a synthesized token whose lexeme is the
// core spelling plus `?` (`Class&?`, `ref:Class?`, `Color?`, `i32?`); decodeSynthesizedType /
// resolveTypeToken decode the suffix. Nested `??` is a parse error.
Token Parser::consumeType() {
    Token base = consumeTypeCore();
    if (match({ TokenType::QUESTION })) {
        if (check(TokenType::QUESTION))
            throw error(peek(), "nested '?\?' is not allowed; a nullable type is written 'T?'");
        // The '&'/'*' suffix must come BEFORE '?', never after (`Class&?`/`Class*?`, not
        // `Class?&`/`Class?*`) — there is only one nullability axis for a reference (the handle
        // itself is either null or points at a fully-formed object; there is no separate "valid
        // handle to an absent object" state), so the reversed order is never meaningful and would
        // otherwise fail later with a confusing, unrelated "expected expression".
        if (check(TokenType::AMPERSAND) || check(TokenType::STAR))
            throw error(peek(), "'" + peek().lexeme + "' must come before '?', not after; write '" +
                                     base.lexeme + peek().lexeme + "?' instead of '" + base.lexeme +
                                     "?" + peek().lexeme + "'");
        return Token{ TokenType::IDENTIFIER, base.lexeme + "?", base.line };
    }
    return base;
}

Token Parser::consumeTypeCore() {
    // A tuple type `(T1, T2, …)` yields a synthesized IDENTIFIER token (the `Tuple$…` class name);
    // otherwise the base is the next type token. Either way, the shared `&`/`*` suffix logic below
    // applies (a tuple has no `<…>` args, so those branches are naturally skipped for it) — so a
    // tuple can be borrowed (`(i32,i32)*`) or owned-referenced (`(i32,i32)&`) like any class.
    Token base = check(TokenType::LEFT_PAREN) ? consumeTupleType() : advance();

    std::string lexeme = base.lexeme;
    int         line   = base.line;
    // `Self` (SELF) and class identifiers are the reference-capable ("class-like") types.
    bool        classLike = base.type == TokenType::IDENTIFIER || base.type == TokenType::SELF;

    // Typed raw pointer: ptr<T> -> synthesized "ptr<elem>" token (internal type).
    if (base.type == TokenType::PTR && check(TokenType::LESS)) {
        std::vector<std::vector<Token>> args = parseTypeArgList();
        std::string elem = args.empty() ? "" : argMangle(args[0]);
        return Token{ TokenType::IDENTIFIER, "ptr<" + elem + ">", line };
    }

    // Generic class instantiation: Name<args> -> mangled concrete class name.
    if (base.type == TokenType::IDENTIFIER && gen_->classNames.count(base.lexeme)
        && check(TokenType::LESS)) {
        std::vector<std::vector<Token>> args = parseTypeArgList();
        std::string mangled = mangleInstantiation(base.lexeme, args);
        recordInstantiation(base.lexeme, mangled, std::move(args));
        classNames.insert(mangled);   // the instantiation is now a concrete class name
        lexeme    = mangled;
        classLike = true;
    }

    if (check(TokenType::AMPERSAND)) {
        bool refOk = base.type == TokenType::SELF || (classLike && classNames.count(lexeme) > 0);
        if (!refOk)
            throw error(peek(), "'&' reference type is only allowed on class types, not '" + lexeme + "'");
        advance();  // consume '&'
        // Synthesize a single reference-type token; resolvers decode the trailing '&'.
        return Token{ TokenType::IDENTIFIER, lexeme + "&", line };
    }

    // Borrow: `T*` → synthesized "ref:T" (a non-owning reference). The inner type may be a
    // class/`Self` or a primitive value type (`i32*`, an lvalue reference to the primitive — like
    // C++'s `int&`; `str*` included — `str` is an ordinary `{ptr,i64}` value type with the same
    // addressable-storage story as any other primitive). `ptr`/`void` cannot be borrowed (opaque,
    // no fixed IR representation to take an lvalue reference to). A generic `T*` reaches here only
    // after monomorphization has substituted T with a concrete type token (which may itself be a
    // mangled generic instantiation, e.g. `Vec$i32*`).
    if (check(TokenType::STAR)) {
        bool primitiveInner = isTypeKeyword(base.type)
                              && base.type != TokenType::PTR && base.type != TokenType::VOID;
        if (!(classLike || primitiveInner))
            throw error(peek(), "'*' borrow is only allowed on class types, `Self`, or a primitive "
                                "like `i32`; `ptr` and `void` cannot be borrowed");
        advance();  // consume '*'
        std::string inner = base.type == TokenType::SELF ? "Self" : lexeme;
        return Token{ TokenType::IDENTIFIER, "ref:" + inner, line };
    }

    if (lexeme != base.lexeme)  // a generic instantiation was mangled
        return Token{ TokenType::IDENTIFIER, lexeme, line };
    return base;
}

// A tuple type `(T1, T2, …)` (arity ≥ 2). Each element is a value or primitive type (v1 rejects
// `&`/`*`/`?`/`ptr` elements so the mangled name is a clean identifier). Produces the canonical
// class name `Tuple$<e1>$<e2>…` (each element lexeme is already a clean identifier — a primitive
// keyword, a class name, or a nested `Tuple$…`), records a one-shot synthesis request keyed by that
// name, and returns it as a single synthesized IDENTIFIER token — an ordinary value-object type to
// everything downstream. `consumeType` recursion handles nesting: `((i32,i32), str)` works.
Token Parser::consumeTupleType() {
    Token lparen = advance();   // '('
    int   line   = lparen.line;

    std::vector<Token> elems;
    do {
        if (!isTypeName())
            throw error(peek(), "expected a type in a tuple type '(T1, T2, …)'");
        Token e = consumeType();
        const std::string& lx = e.lexeme;
        bool badSigil = (!lx.empty() && (lx.back() == '&' || lx.back() == '?'))
                     || lx.rfind("ref:", 0) == 0
                     || lx == "ptr" || lx.rfind("ptr<", 0) == 0
                     || lx == "void";
        if (badSigil)
            throw error(e, "tuple elements must be value or primitive types in v1 "
                           "(no '&', '*', '?', or raw pointers); found '" + lx + "'");
        elems.push_back(e);
    } while (match({ TokenType::COMMA }));

    consume(TokenType::RIGHT_PAREN, "expected ')' to close a tuple type");

    if (elems.size() < 2)
        throw error(lparen, "a tuple type needs at least two elements; '(T)' is just grouping "
                            "and '()' is reserved");

    std::string mangled = "Tuple";
    for (const Token& e : elems) mangled += "$" + e.lexeme;

    classNames.insert(mangled);
    gen_->classNames.insert(mangled);
    if (gen_->tupleRequests.find(mangled) == gen_->tupleRequests.end()) {
        std::vector<Token> copy;
        copy.reserve(elems.size());
        for (const Token& e : elems) copy.push_back(e);   // Token copy-ctor is fine (only assign is deleted)
        gen_->tupleRequests.emplace(mangled, std::move(copy));
    }
    return Token{ TokenType::IDENTIFIER, mangled, line };
}

// ============================================================
// Statement parsers
// ============================================================

Stmt Parser::parseDeclaration() {
    // A leading `@Name(...)` in declaration position is an annotation applied to the following
    // class. Disambiguated from statement-level reflection builtins (`@compileError`, …) by CASE:
    // annotation types are Capitalized, builtins are lowercase. A lowercase `@…` falls through to
    // parseStatement (an expression statement) below.
    if (check(TokenType::AT) && peekNext().type == TokenType::IDENTIFIER
        && !peekNext().lexeme.empty() && std::isupper(static_cast<unsigned char>(peekNext().lexeme[0]))) {
        std::deque<AnnotationApp> anns = parseAnnotationPrefixes();
        Token where = previous();
        if (match({ TokenType::CLASS })) {
            Stmt s = parseClassDecl();
            std::get<ClassDeclStmt>(*s.node).annotations = std::move(anns);
            return s;
        }
        if (match({ TokenType::ENUM })) {
            Stmt s = parseEnumDecl();
            // enum-level annotations are recorded on… v1 has no enum-type annotation slot beyond
            // variants, so reject to keep the surface honest.
            (void)anns;
            throw error(where, "annotations on an 'enum' type are not supported; annotate its "
                               "variants or fields instead");
        }
        throw error(where, "an annotation here must prefix a 'class' declaration");
    }

    // extern returnType name( params );
    if (match({ TokenType::IMPORT })) {
        Token keyword = previous();
        return parseImportStmt(keyword);
    }

    if (match({ TokenType::EXTERN })) {
        Token keyword = previous();
        return parseExternFuncDecl(keyword);
    }

    if (match({ TokenType::CLASS })) {
        return parseClassDecl();
    }

    if (match({ TokenType::ENUM })) {
        return parseEnumDecl();
    }

    if (match({ TokenType::ANNOTATION })) {
        return parseAnnotationDecl();
    }

    if (match({ TokenType::TRAIT })) {
        return parseTraitDecl();
    }

    if (match({ TokenType::IMPL })) {
        return parseImplDecl();
    }

    // Every function declaration begins with `fn`.
    if (match({ TokenType::FN })) {
        return parseFnDeclaration();
    }
    return parseStatement();
}

void Parser::recordLocal(const Token& typeToken, const Token& name) {
    if (!scopes_.empty()) scopes_.back().emplace(name.lexeme, typeToken);
}

Stmt Parser::parseImportStmt(const Token& keyword) {
    Token path = consume(TokenType::STRING, "expected file path string after 'import'");
    consume(TokenType::SEMICOLON, "expected ';' after import path");
    return makeStmt(ImportStmt{ keyword, path });
}

Stmt Parser::parseStatement() {
    if (check(TokenType::LEFT_BRACE))   return parseBlock();
    if (match({ TokenType::IF     }))   return parseIfStmt();
    if (match({ TokenType::WHILE  }))   return parseWhileStmt();
    if (match({ TokenType::FOR    }))   return parseForStmt();
    if (match({ TokenType::INLINE }))   return parseInlineForStmt();
    if (match({ TokenType::RETURN }))   return parseReturnStmt();
    if (match({ TokenType::BREAK }))    return parseBreakStmt();
    if (match({ TokenType::CONTINUE })) return parseContinueStmt();
    if (match({ TokenType::SWITCH }))   return parseSwitchStmt();
    if (match({ TokenType::MATCH }))    return parseMatchStmt();
    if (match({ TokenType::YIELD }))    return parseYieldStmt();
    return parseExprStmt();
}

BlockStmt Parser::parseBlockBody() {
    // Called after '{' has already been consumed. Opens a lexical scope (for lambda capture
    // analysis), seeded with any pending params from the enclosing function/lambda signature.
    scopes_.emplace_back();
    for (auto& [n, t] : pendingScopeSeed_) scopes_.back().emplace(n, t);
    pendingScopeSeed_.clear();

    std::vector<std::unique_ptr<Stmt>> body;
    while (!check(TokenType::RIGHT_BRACE) && !isAtEnd()) {
        body.push_back(std::make_unique<Stmt>(parseDeclaration()));
    }
    consume(TokenType::RIGHT_BRACE, "expected '}'");
    scopes_.pop_back();
    return BlockStmt{ std::move(body) };
}

Stmt Parser::parseBlock() {
    consume(TokenType::LEFT_BRACE, "expected '{'");
    return makeStmt(parseBlockBody());
}